### ISSUE TITLE
undefined reference to `SEGGER_RTT_WriteString'

### ISSUE THREAD

**Issue by sirceljm** [monpetit/inventus-factory-examples#1]
Hi,

first let me say thanks for publishing this project. It is the only way that I managed to get my BLE400 working. 

Now to the problem.

I managed to build, upload the softdevice and then get the bluetooth signal. Now I want to use SEGGER_RTT_WriteString to start debugging the program. I included the headers like so: 
#include "SEGGER_RTT.h" and I put SEGGER_RTT_WriteString(0, "Hello World!\n"); inside main function.

But I get an error: undefined reference to `SEGGER_RTT_WriteString'

Do you maybe know how to get this working as I see the SEGGER_RTT files are already there.

Please excuse me if this is a really stupid question but I am completely new to this.

**Comment by monpetit** [comment]
Hello,

It seems like preprocessor definitions don't contain NRF_LOG_USES_RTT=1. You should modify the definition of NRF_LOG_USES_xxx(NRF_LOG_USES_UART=1) to NRF_LOG_USES_RTT=1.

By the way, I sensed RTT files of this project is somewhat old that missing SEGGER_RTT_printf.c. So I just updated RTT files. You can use this example with SEGGER Embedded Studio now. Don't forget modify preprocessor definitions. Have fun. =)

**Comment by sirceljm** [comment]
It works perfectly. Thanks!
